// AUTO-GENERATED by scripts/generate_contract_types.py. Do not edit manually.
// Source of truth: backend/app/core/contracts.py

export type StageId = "S0" | "S1" | "S2" | "S3" | "S4" | "S5" | "S6" | "S7" | "S8" | "S9";
export type StageStatus = "completed" | "skipped" | "no_op" | "paused" | "blocked" | "failed";
export type TurnStatus = "accepted" | "running" | "waiting_clarification" | "waiting_approval" | "paused" | "recovery_pending" | "needs_manual" | "completed" | "failed" | "cancelled" | "blocked";
export type ApprovalStatus = "pending_first" | "first_confirmed" | "pending_second" | "approved" | "rejected" | "expired" | "consumed" | "invalidated";
export type ArtifactStatus = "building" | "verified" | "preview_ready" | "failed" | "deleted";
export type DeploymentStatus = "pending" | "uploading" | "health_checking" | "succeeded" | "failed";
export type RiskLevel = "low" | "mid" | "high" | "critical";

export interface StageResult {
  schema_version: "1.0";
  stage: StageId;
  status: StageStatus;
  reason_code: string;
  input_schema_version: string;
  output_schema_version: string;
  entered_at: string;
  left_at: string;
  duration_ms: number;
  output_refs: string[];
}

export interface StreamEvent {
  schema_version: "1.0";
  stream_id: string;
  turn_id: string;
  trace_id: string;
  event_id: string;
  seq: number;
  timestamp: string;
  type: "stage" | "task" | "tool" | "token" | "retract" | "think" | "gen_token" | "gen_think" | "state_diff" | "approval" | "attempt_output" | "suspended" | "usage" | "capability_notice" | "error" | "reconnect" | "done";
  data: Record<string, unknown>;
}
