"""从 M2 Python 契约生成前端最小 TypeScript 类型。

用法：
    PYTHONPATH=backend python scripts/generate_contract_types.py --write
    PYTHONPATH=backend python scripts/generate_contract_types.py --check
"""

from __future__ import annotations

import argparse
from pathlib import Path

from app.core.contracts import (
    ApprovalStatus,
    ArtifactStatus,
    DeploymentStatus,
    RiskLevel,
    StageId,
    StageStatus,
    TurnStatus,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = PROJECT_ROOT / "frontend" / "src" / "types" / "contracts.generated.ts"


def union(enum_type: type[object]) -> str:
    values = [member.value for member in enum_type]  # type: ignore[attr-defined]
    return " | ".join(f'"{value}"' for value in values)


def render() -> str:
    return f"""// AUTO-GENERATED by scripts/generate_contract_types.py. Do not edit manually.
// Source of truth: backend/app/core/contracts.py

export type StageId = {union(StageId)};
export type StageStatus = {union(StageStatus)};
export type TurnStatus = {union(TurnStatus)};
export type ApprovalStatus = {union(ApprovalStatus)};
export type ArtifactStatus = {union(ArtifactStatus)};
export type DeploymentStatus = {union(DeploymentStatus)};
export type RiskLevel = {union(RiskLevel)};

export interface StageResult {{
  schema_version: "1.0";
  stage: StageId;
  status: StageStatus;
  reason_code: string;
  input_schema_version: string;
  output_schema_version: string;
  entered_at: string;
  left_at: string;
  duration_ms: number;
  output_refs: string[];
}}

export interface StreamEvent {{
  schema_version: "1.0";
  stream_id: string;
  turn_id: string;
  trace_id: string;
  event_id: string;
  seq: number;
  timestamp: string;
  type: "stage" | "task" | "tool" | "token" | "state_diff" | "approval" | "attempt_output" | "suspended" | "usage" | "capability_notice" | "error" | "reconnect" | "done";
  data: Record<string, unknown>;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"Contract type output is stale: {OUTPUT}")
            return 1
        print(f"Contract type output is current: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
